// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hsejqpvvohwzigpcmlrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzZWpxcHZ2b2h3emlncGNtbHJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMjI3NjUsImV4cCI6MjA3ODY5ODc2NX0.D4MzYHqWQp7ihZB0dwCL4Hrf7qlf38VkozfOoEtuYqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);