// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://craxxcgrjbadtyiptsyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyYXh4Y2dyamJhZHR5aXB0c3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0ODE3MjYsImV4cCI6MjA3OTA1NzcyNn0.wYPsNiQqmUwM8nidTAt5NVD228rwwEYFsY8mI403HPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);